namespace: dev


resources:
- namespace.yaml
- cm-userpod.yaml
- config.yaml
- ../../base/
- kipac-pvcs.yaml
- sdf-home-pvc.yaml


configMapGenerator:
- files:
  - etc/templates/default.yaml
  - etc/templates/ldmx.yaml
  - etc/templates/supercdms.yaml
  - etc/templates/kipac.yaml
  name: templates
  options:
    disableNameSuffixHash: true
- files:
  - etc/sssd.conf
  - etc/krb5.conf
  #- etc/nslcd.conf
  name: sssd
- files:
  - etc/sshd_config
  name: sshd

secretGenerator:
- files:
  - etc/ssh_host_ecdsa_key
  - etc/ssh_host_ecdsa_key.pub
  - etc/ssh_host_ed25519_key
  - etc/ssh_host_ed25519_key.pub
  - etc/ssh_host_rsa_key
  - etc/ssh_host_rsa_key.pub
  name: ssh-hostkeys

images:
- name: slaclab/session-gateway 
  newTag: 20250918-1515

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: service-patch.yaml
