apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sdf-home
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sdf-home
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi

