resources:
- deployment.yaml
- role.yaml 
- rolebinding.yaml 
- service.yaml
- serviceaccount.yaml
- pvc.yaml

configMapGenerator:
- name: templates
  files:
  - templates/default.yaml
  - templates/ldmx.yaml


#configMapGenerator:
#- name: sssd
#  files:
#  - etc/sssd.conf
#  - etc/nslcd.conf
#  - etc/krb5.conf
#secretGenerator:
#- name: sshd
#  files:
#  - etc/ssh_host_ecdsa_key
#  - etc/ssh_host_ecdsa_key.pub
#  - etc/ssh_host_ed25519_key
#  - etc/ssh_host_ed25519_key.pub
#  - etc/ssh_host_rsa_key
#  - etc/ssh_host_rsa_key.pub
