kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: session-gateway
rules:
- apiGroups: [""]
  resources: ["configmaps" ]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
#- apiGroups: [""]
#  resources: ["pods/attach"]
#  verbs: ["get", "create"]
#- apiGroups: ["apps"]
#  resources: ["deployments"]
#  verbs: ["get", "list", "watch", "create", "delete"]
