kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: session-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: session-gateway
subjects:
  - kind: ServiceAccount
    name: session-gateway
