apiVersion: v1
kind: Service
metadata:
  labels:
    app: session-gateway
  name: session-gateway
spec:
  ports:
  - nodePort: 32222
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: session-gateway
  type: NodePort
